version: "3.3"
services:

  db:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example!!!&&
      MYSQL_DATABASE: test
      MYSQL_USER: ficr
      MYSQL_PASSWORD: ficr1234
    ports:
      - 9999:3306  
    volumes:
       - ./db-files:/var/lib/mysql

  web:
    working_dir: /home/app
    image: node:20-bullseye
    restart: always
    ports:
      - 80:3000
    volumes:
      - .:/home/app
    command: "npm start"

  
